version: "3.9"
services:
  cv_maker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv_maker
    ports:
      - '3000:3000' # dev build
    volumes:
      - .:/srv/
      # - ./node_modules:/srv/node_modules
    tty: true
